version: "3"

services:
  fail2ban:
    # https://github.com/crazy-max/docker-fail2ban/tree/master/examples/jails/sshd
    image: crazymax/fail2ban:latest
    restart: always
    container_name: fail2ban
    volumes:
      - /etc/fail2ban:/data
      - /var/log:/var/log:ro
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/London
      - F2B_IPTABLES_CHAIN=INPUT
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
