version: "3"

services:
  fail2ban:
    # https://github.com/crazy-max/docker-fail2ban/tree/master/examples/jails/sshd
    image: crazymax/fail2ban:latest
    restart: always
    container_name: fail2ban
    volumes:
      - /etc/fail2ban:/data
      - /var/log:/var/log:ro
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/London
      - F2B_IPTABLES_CHAIN=INPUT
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO

  nginx_proxy:
    # https://hub.docker.com/r/jwilder/nginx-proxy/
    image: jwilder/nginx-proxy:latest
    restart: always
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx_proxy_letsencrypt:
    # https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - nginx_proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=simjenner3@gmail.com
      - DEBUG=True

  portainer:
    image: portainer/portainer:latest
    restart: unless-stopped
    container_name: portainer
    depends_on:
      - nginx_proxy_letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=pt.simonj.tech
      - LETSENCRYPT_HOST=pt.simonj.tech

  redirect:
    image: morbz/docker-web-redirect:latest
    restart: unless-stopped
    container_name: github-web-redirect
    depends_on:
      - nginx_proxy_letsencrypt
    environment:
      - REDIRECT_TARGET=https://github.com/psidex
      - VIRTUAL_HOST=simonj.tech
      - LETSENCRYPT_HOST=simonj.tech

volumes:
  portainer_data:
  vhost:
  html:
  certs:
