#!/usr/bin/env bash

# This script assumes you:
#  - Are running Debian 10
#  - Have the `sudo` and `git` packages installed
#  - Are running it as a normal user that is a member of the `sudo` group

# Pull latest versions of all images
# sudo docker-compose pull
# Re-build and run all containers
# sudo docker-compose up --build -d
# Remove "dangling" (currently unused) images
# sudo docker image prune

sudo passwd -l root

sudo timedatectl set-timezone UTC

sudo apt update
sudo apt upgrade -y
sudo apt install ufw lolcat figlet fortune fortunes unattended-upgrades -y

# Warning: Docker containers ignore UFW rules.
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
sudo systemctl restart ufw

# /etc/motd can contain a warranty message.
sudo rm /etc/motd
sudo rm /etc/update-motd.d/*
sudo cp ./motd/* /etc/update-motd.d/
chmod +x /etc/update-motd.d/*

# --- Install Caddy --- #

curl https://getcaddy.com | bash -s personal.

sudo mkdir -p /etc/caddy/Caddyfile
sudo mkdir -p /var/www/html

sudo cp ./caddy/Caddyfile /etc/caddy/Caddyfile
sudo cp ./site/* /var/www/html

sudo cp ./caddy/caddy.serivce /etc/systemd/system

# https://github.com/caddyserver/dist/tree/master/init
groupadd --system caddy
useradd --system --gid caddy --create-home --home-dir /var/lib/caddy 
    --shell /usr/sbin/nologin --comment "Caddy web server" caddy

sudo systemctl enable caddy
sudo systemctl start caddy

# --- End Install Caddy --- #

# --- Begin Docker setup --- #

sudo apt install \
    apt-transport-https ca-certificates curl gnupg2 software-properties-common -y

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y

# Install Docker Compose.
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# --- End Docker setup --- #

sudo mkdir -p /etc/fail2ban/jail.d
sudo cp ./fail2ban/sshd.conf /etc/fail2ban/jail.d

sudo docker-compose up -d

echo "Setup done"
