#!/usr/bin/env bash

# This script assumes you:
#  - Are running Debian 10
#  - Have the `sudo` and `git` packages installed
#  - Are running it as a normal user that is a member of the `sudo` group

sudo passwd -l root
sudo timedatectl set-timezone UTC

# Local scripts

chmod +x ./siteupdate
chmod +x ./sitemetrics

# Install goaccess repo

echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/goaccess.gpg add -

# Install everything we need from apt

sudo apt update
sudo apt upgrade -y
sudo apt install ufw lolcat figlet fortune fortunes fail2ban goaccess jq unattended-upgrades -y

# Fail2ban.
sudo cp -a ./fail2ban/. /etc/fail2ban/jail.d/
sudo systemctl restart fail2ban

# Warning: Docker containers ignore UFW rules.
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
sudo systemctl restart ufw

# Setup MOTD.
# /etc/motd can contain a warranty message.
sudo rm /etc/motd
sudo rm /etc/update-motd.d/*
sudo cp ./motd/* /etc/update-motd.d/
chmod +x /etc/update-motd.d/*

# Install Docker.
sudo apt install \
    apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y

# Setup Docker stuff.
docker network create proxynet
docker volume create caddy
docker volume create psmdata

# Start Docker stuff.
docker run -d --name gostatic --restart unless-stopped \
    -v $(pwd)/site/public:/srv/http \
    --network proxynet \
    pierrezemb/gostatic

docker run -d --name psmserver \
    --network proxynet \
    -v psmdata:/data \
    psidex/portsmouthshippingmovements

docker run -d --name msserver \
    --network proxynet \
    psidex/messengerstats

docker run -d --name spacexlaunchbotsite --restart unless-stopped \
    --network proxynet \
   psidex/spacexlaunchbotsite

docker run -d --name caddy --restart unless-stopped \
    -p 80:80 -p 443:443 \
    -v $(pwd)/caddy/Caddyfile:/etc/caddy/Caddyfile \
    -v $(pwd)/caddy/log:/var/log/caddy \
    -v caddy:/data \
    --network proxynet \
    caddy

# See https://github.com/containrrr/watchtower/issues/669#issuecomment-721885754
docker run -d --name watchtower --restart unless-stopped \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e "WATCHTOWER_POLL_INTERVAL=2160" \
    containrrr/watchtower

echo "Setup done"

# Post Install:
#
# `unattended-upgrades` is installed but not setup, see the link for setup guide:
# https://libre-software.net/ubuntu-automatic-updates/
#
# portsmouthshippingmovements will require a `config.json` file in it's volume and will
# then need to be restarted
