#!/usr/bin/env bash

# This script assumes you:
#  - Are running Debian 10
#  - Have the `sudo` and `git` packages installed
#  - Are running it as a normal user that is a member of the `sudo` group

sudo passwd -l root
sudo timedatectl set-timezone UTC

sudo apt update
sudo apt upgrade -y
sudo apt install ufw lolcat figlet fortune fortunes unattended-upgrades -y

# Warning: Docker containers ignore UFW rules.
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
sudo systemctl restart ufw

# /etc/motd can contain a warranty message.
sudo rm /etc/motd
sudo rm /etc/update-motd.d/*
sudo cp ./motd/* /etc/update-motd.d/
chmod +x /etc/update-motd.d/*

# Docker.
sudo apt install \
    apt-transport-https ca-certificates curl gnupg2 software-properties-common -y
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y

# Where to store files and directories that containers will reference.
CONTAINER_FILES_DIR="/etc/dockercontainerfiles"
FAIL2BAN_DIR="${CONTAINER_FILES_DIR}/fail2ban"
FAIL2BAN_JAIL_DIR="${FAIL2BAN_DIR}/jail.d"
CADDY_DIR="${CONTAINER_FILES_DIR}/caddy"
SITE_DIR="${CONTAINER_FILES_DIR}/site"

sudo mkdir $CONTAINER_FILES_DIR
sudo mkdir $FAIL2BAN_DIR
sudo mkdir $FAIL2BAN_JAIL_DIR
sudo mkdir $CADDY_DIR
sudo mkdir $SITE_DIR

# Build site
docker run --rm -it -v $(pwd)/site:/src klakegg/hugo:0.71.0

sudo cp -R ./jails/. $FAIL2BAN_JAIL_DIR
sudo cp -R ./caddy/. $CADDY_DIR
sudo cp -R ./site/public/. $SITE_DIR

# A network for all apps that require reverse proxying through Caddy.
docker network create proxynet

docker run -d --name fail2ban --restart always \
    -v $FAIL2BAN_DIR:/data \
    -v /var/log:/var/log:ro \
    --network=host \
    --cap-add NET_ADMIN \
    --cap-add NET_RAW \
    -e TZ="UTC" \
    -e F2B_IPTABLES_CHAIN="INPUT" \
    -e F2B_LOG_TARGET="STDOUT" \
    -e F2B_LOG_LEVEL="INFO" \
    crazymax/fail2ban

docker run -d --name static-site --restart unless-stopped \
    -v $SITE_DIR:/srv/http \
    --network proxynet \
    pierrezemb/gostatic

docker run -d --name caddy --restart unless-stopped \
    -p 80:80 -p 443:443 \
    -v "${CADDY_DIR}/Caddyfile":/etc/caddy/Caddyfile \
    -v "${CADDY_DIR}/data":/data \
    --network proxynet \
    caddy

docker run -d --name watchtower --restart unless-stopped \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower

echo "Setup done"

cp ./update-site ~
chmod +x ~/update-site

sudo rm -rf ~/Apollo

echo "Update script moved to ~ and ~/Apollo removed"
