#!/usr/bin/env bash

# Script heavily edited from https://alexmv12.xyz/blog/goaccess_caddy/

jq --raw-output '[
         .common_log,
         .request.headers.Referer[0] // "-",
         .request.headers."User-Agent"[0],
         .duration
   ] | @csv' \
   ./caddy/log/*.log \
   > ./everything.log

goaccess ./everything.log \
   --log-format='"%h - - [%d:%t %^] ""%m %r %H"" %s %b","%R","%u",%T' \
   --time-format='%H:%M:%S' --date-format='%d/%b/%Y'

rm ./everything.log
