#!/usr/bin/env bash

# Updates the static site files.

SITE_DIR="/etc/dockercontainerfiles/site"

git clone --recurse-submodules https://github.com/psidex/Apollo ~/Apollo

sudo docker run --rm -it -v ~/Apollo/site:/src klakegg/hugo:0.71.0

sudo cp -R ~/Apollo/site/public/. $SITE_DIR

sudo rm -rf ~/Apollo
