baseurl = "https://simonj.tech/"
title = "Simon Jenner"
theme = "pulp"
canonifyurls = true

[params]
    author = "Simon Jenner"
    avatar = "avatar.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        Software Engineering student at the University of Portsmouth.
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
# [outputs]
#     section = ["JSON", "HTML"]
#     taxonomy = ["JSON", "HTML"]

# [[menu.main]]
#     identifier = "twitter"
#     # name = "Twitter"
#     pre = "<i class='fab fa-twitter fa-lg'></i>"
#     url = "https://twitter.com/psidex_"
#     weight = 10

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<img src='/img/github.svg'>"
    url = "https://github.com/psidex"
    weight = 20

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<img src='/img/mail.svg'>"
    url = "mailto:simjenner3@gmail.com"
    weight = 30

[[menu.main]]
    identifier = "psm"
    pre = "<img src='/img/anchor.svg'>"
    url = "https://psm.simonj.tech/"
    weight = 30

[[menu.main]]
    identifier = "messenger"
    pre = "<img src='/img/message-circle.svg'>"
    url = "https://messenger.simonj.tech/"
    weight = 30
