baseurl = "https://simonj.tech/"
title = "Simon Jenner"
theme = "pulp"
canonifyurls = true

[params]
    author = "Simon Jenner"
    avatar = "avatar.jpg"
    # avatarDescription = "My avatar description"
    favicon = "/favicon.ico"
    description = """
        Software Engineering student at the University of Portsmouth.
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/pulp-custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
# [outputs]
#     section = ["JSON", "HTML"]
#     taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<img class='home-image-link' src='/img/github.svg'>"
    url = "https://github.com/psidex"
    weight = 30

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<img class='home-image-link' src='/img/mail.svg'>"
    url = "mailto:simjenner3@gmail.com"
    weight = 30

[[menu.main]]
    identifier = "keybase"
    name = "Keybase"
    pre = "<img class='home-image-link' src='/img/key.svg'>"
    url = "https://keybase.io/psidex/"
    weight = 30

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    pre = "<img class='home-image-link' src='/img/book.svg'>"
    url = "https://simonj.tech/projects.html"
    weight = 30
