version: "3"

services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
