version: "3"

services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer
    networks:
      - nginx_web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_web
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d

networks:
  nginx_web:

volumes:
  portainer_data:
