#!/usr/bin/env bash

sudo passwd -l root

sudo apt update
sudo apt upgrade -y
sudo apt install ufw lolcat figlet fortune -y

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
sudo systemctl restart ufw

# Clear warranty message.
sudo rm /etc/motd && touch /etc/mot

chmod +x motd/*
sudo rm /etc/update-motd.d/*
sudo cp motd/* /etc/update-motd.d/

# Force MOTD update
sudo run-parts /etc/update-motd.d/

# Docker setup

sudo apt-get install \
    apt-transport-https ca-certificates curl gnupg2 software-properties-common -y

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y

# Portainer
sudo docker volume create portainer_data
sudo docker run -d --name=portainer --restart=always \
    -p 8000:8000 -p 9000:9000 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer

# Fail2Ban
sudo docker run -d --name fail2ban --restart always \
  --network host \
  --cap-add NET_ADMIN \
  --cap-add NET_RAW \
  -v $(pwd)/data:/data \
  -v /var/log:/var/log:ro \
  crazymax/fail2ban:latest

# End Docker setup

echo "Setup done"
