#!/usr/bin/env bash

sudo passwd -l root

sudo apt update
sudo apt upgrade -y
sudo apt install ufw fail2ban lolcat figlet fortune -y

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable
sudo systemctl restart ufw

sudo cp ./jail.local /etc/fail2ban/jail.local
sudo systemctl restart fail2ban

# Clear warranty message.
sudo rm /etc/motd && touch /etc/mot

chmod +x motd/*
sudo rm /etc/update-motd.d/*
sudo cp motd/* /etc/update-motd.d/

# Force MOTD update
sudo run-parts /etc/update-motd.d/

# Docker setup

sudo apt-get install \
    apt-transport-https ca-certificates curl gnupg2 software-properties-common -y

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y

# Install Docker Compose.
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Current user can run docker commands without sudo after re-log.
sudo groupadd docker
sudo usermod -aG docker $USER

# End Docker setup

sudo docker-compose up -d

echo "Setup done"
